# Site settings
title: Aditya Wagh
tagline: On a quest to make intelligent machines!
author: Aditya Wagh
twitter:
  username: adityamwagh
  card: summary
logo: /assets/images/icon.png
social:
  name: Aditya Wagh
  links:
    - https://twitter.com/adityamwagh
    - https://www.facebook.com/adityamwagh
    - https://www.linkedin.com/in/adityamwagh
    - https://github.com/adityamwagh

lang: en-US
resume_link: https://raw.githubusercontent.com/adityamwagh/cv/master/AdityaWagh_CV.pdf
baseurl: ""
url: "https://www.adityawagh.ml/"
firstname: Aditya
secondname: Wagh
general_email: adityamwagh@gmail.com

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block:
      line_numbers: false
sass:
  style: compressed

# Other options
permalink: blog/:title

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/