# Site settings
title: Aditya Wagh
general_email: aditya@adityawagh.ml
academic_email: f2015382p@alumni.bits-pilani.ac.in

description:
  A curious engineer hoping to solve important problems in the world using technology.
baseurl: ""

url: "https://www.adityawagh.ml/" 

twitter_username: ad1tyawagh
github_username: ad1tyawagh
linkedin_username: waghaditya

# Build settings
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax


# Other options
permalink: blog/:year/:month/:title

gems:
  - jekyll-font-awesome-sass
plugins:
- github-pages,
- jekyll-seo-tag
- jekyll-menus, '~> 0.6.1'
- jekyll-seo-tag,
- jekyll-remote-theme, 
- jekyll-archives,
- jekyll-compose, 
- jemoji,
- jekyll-youtube,
- jekyll-seo-tag 
