# Site settings
title: Aditya Wagh
general_email: aditya@adityawagh.ml
academic_email: f2015382p@alumni.bits-pilani.ac.in

description:
  A curious engineer hoping to solve important problems in the world using technology.
baseurl: ""

url: "https://www.adityawagh.ml/" 

twitter_username: ad1tyawagh
github_username: ad1tyawagh
linkedin_username: waghaditya

# Build settings
markdown: kramdown
mathjax: true
kramdown:
  math_engine: mathjax


# Other options
permalink: blog/:year/:month/:title
