# Site settings
title: Aditya Wagh
general_email: adityamwagh@gmail.com
academic_email: f2015382@pilani.bits-pilani.ac.in

description: > # this means to ignore newlines until "baseurl:"
  Recent college graduate hoping to solve important problems in the world using technology. I wish to contribute to the fields of prosthetics, energy efficient systems and electric vehicles. 

baseurl: "" 

url: "https://www.adityawagh.ml/" # the base hostname & protocol for your site

twitter_username: ad1tyawagh
github_username: ad1tyawagh
linkedin_username: waghaditya
facebook_username: ad1tyawagh
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
